apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: todo
        env:
        - name: quarkus.otel.exporter.otlp.endpoint
          value: http://otel-collector-headless:4317