#namePrefix: prod-
commonAnnotations:
  description: This is Production environment
resources:
- todo-hpa.yaml
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    environment: prod
patches:
- path: todo.yaml
