apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 5
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec: # sidecar.opentelemetry.io/inject: "true" 
      containers:
      - name: todo
        env:
        - name: quarkus.otel.exporter.otlp.endpoint
          value: http://localhost:4317