apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation
spec:
  exporter:
    endpoint: 'http://otel-collector-headless:4318'
  java:
    env:
      - name: OTEL_JAVAAGENT_DEBUG
        value: debug
      - name: OTEL_METRICS_EXPORTER
        value: none
  sampler:
    type: always_on
  env:
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
  propagators:
    - b3
