apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
    serviceAccount: otel-collector
    config: |
      extensions:
        bearertokenauth:
          filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      exporters:
        # Export the dev tenant traces to a Tempo instance
        otlp/dev:
          endpoint: tempo-simplest-gateway.PROJECT.svc.cluster.local:8090
          tls:
            insecure: false
            ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
          auth:
            authenticator: bearertokenauth
          headers:
            X-Scope-OrgID: "dev"

      receivers:
        otlp:
          protocols:
            grpc:
            http:
        jaeger:
          protocols:
            thrift_binary:
            thrift_compact:
            thrift_http:
            grpc:

      service:
        extensions: [bearertokenauth]
        pipelines:
          traces:
            receivers: [otlp, jaeger]
            exporters: [otlp/dev]