apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  labels:
    app.kubernetes.io/managed-by: opentelemetry-operator
spec:
  observability:
    metrics:
      enableMetrics: true
  config: |
    receivers:
      otlp:
        protocols: 
          grpc:
          http:

    exporters:
      otlp:
        endpoint: "jaeger-collector-headless:4317"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
  mode: deployment
  resources: {}
  minReplicas: 1
  managementState: managed
  upgradeStrategy: none
  ingress:
    route: {}
  autoscaler:
    maxReplicas: 4
    minReplicas: 2
    targetCPUUtilization: 90
  targetAllocator:
    prometheusCR:
      scrapeInterval: 30s
    resources: {}
  replicas: 1
  updateStrategy: {}
  podDisruptionBudget:
    maxUnavailable: 1