apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  observability:
    metrics:
      enableMetrics: true
  config:
    connectors:
      spanmetrics: 
        metrics_flush_interval: 15s
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      jaeger:
        protocols:
          thrift_binary:  {}
          thrift_compact:  {}
          thrift_http:  {}
          grpc: {}
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      otlp:
        endpoint: tempo-simplest-distributor.PROJECT.svc.cluster.local:4317
        tls:
          insecure: true
          #ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"   
      prometheus: 
        endpoint: 0.0.0.0:8889
        add_metric_suffixes: false
        resource_to_telemetry_conversion:
          enabled: true     
      # debug: {}

    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: [memory_limiter, batch]
          exporters: [otlp, spanmetrics]
        metrics:
          receivers: [spanmetrics]
          exporters: [prometheus]
