apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo
spec:
  endpoints:
  - interval: 30s
    port: http
    path: /q/metrics
    scheme: http
  - interval: 30s
    port: http
    path: /q/metrics/application
    scheme: http
  selector:
    matchLabels:
      app: todo