apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic 
metadata:
  name: simplest
spec:
  retention:
    global:
      traces: 72h # Default is 48 hours
  observability:
    metrics:
      createServiceMonitors: true
      createPrometheusRules: true
  storage: 
    traces:
      backend: pv
      size: 2Gi 
      # s3: 
      #   secret: <secret_name> 
    # tls: 
    #   enabled: true
    #   caName: <ca_certificate_configmap_name> 
  jaegerui:
    enabled: true 
    route:
      enabled: true 
  resources: 
    total:
      limits:
        memory: 1Gi
        cpu: 1000m
  multitenancy:
    enabled: true
    mode: openshift
    authentication: 
      - tenantName: dev 
        tenantId: "1610b0c3-c509-4592-a256-a1871353dbfa" 
      - tenantName: prod
        tenantId: "1610b0c3-c509-4592-a256-a1871353dbfb"
  template:
    gateway:
      enabled: true
    queryFrontend:
      jaegerQuery:
        enabled: true
        monitorTab:
          enabled: true 
          prometheusEndpoint: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempostack-traces-write
rules:
  - apiGroups:
      - 'tempo.grafana.com'
    resources:
      - dev
    resourceNames:
      - traces
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempostack-traces-reader
rules:
  - apiGroups:
      - 'tempo.grafana.com'
    resources:
      - dev
      - prod
    resourceNames:
      - traces
    verbs:
      - 'get'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tempostack-traces-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tempostack-traces-reader
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:authenticated
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempostack-traces-write
rules:
  - apiGroups:
      - 'tempo.grafana.com'
    resources:
      - dev
      - prod
    resourceNames:
      - traces
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tempostack-traces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tempostack-traces-write
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: PROJECT
# apiVersion: tempo.grafana.com/v1alpha1
# kind: TempoMonolithic
# metadata:
#   name: simplest
# spec:
#   observability:
#     # metrics:
#     #   prometheusRules:
#     #     enabled: true
#     #   serviceMonitors:
#     #     enabled: true
#     metrics:
#       createServiceMonitors: true
#       createPrometheusRules: true
#   ingestion:
#     otlp:
#       grpc:
#         enabled: true
#       http:
#         enabled: true
#   resources:
#     limits:
#       cpu: '2'
#       memory: 2Gi
#   jaegerui:
#     authentication:
#       enabled: true
#     resources:
#       limits:
#         cpu: '2'
#         memory: 2Gi
#     route:
#       enabled: true
#       termination: edge
#     enabled: true
#   storage:
#     traces:
#       backend: pv
#   template:
#     queryFrontend:
#       jaegerQuery:
#         enabled: true
#         monitorTab:
#           enabled: true 
#           prometheusEndpoint: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091 
#         ingress:
#           type: route
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: tempostack-traces-write
# rules:
#   - apiGroups:
#       - 'tempo.grafana.com'
#     resources:
#       - dev
#     resourceNames:
#       - traces
#     verbs:
#       - 'create'
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: tempostack-traces-reader
# rules:
#   - apiGroups:
#       - 'tempo.grafana.com'
#     resources:
#       - dev
#       - prod
#     resourceNames:
#       - traces
#     verbs:
#       - 'get'
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: tempostack-traces-reader
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: tempostack-traces-reader
# subjects:
#   - kind: Group
#     apiGroup: rbac.authorization.k8s.io
#     name: system:authenticated
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: otel-collector
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: tempostack-traces-write
# rules:
#   - apiGroups:
#       - 'tempo.grafana.com'
#     resources:
#       - dev
#       - prod
#     resourceNames:
#       - traces
#     verbs:
#       - 'create'
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: tempostack-traces
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: tempostack-traces-write
# subjects:
#   - kind: ServiceAccount
#     name: otel-collector
#     namespace: PROJECT