#namePrefix: prod-
commonAnnotations:
  description: This is Dev environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
labels:
- includeSelectors: true
  pairs:
    environment: dev
patches:
- path: todo.yaml
