apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 5
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
      - name: todo
        image: quay.io/voravitl/todo:v1
        resources:
          limits:
            cpu: 300m
            memory: 700Mi
          requests:
            cpu: 200m
            memory: 300Mi