apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: todo
        env:
        - name: quarkus.opentelemetry.tracer.exporter.otlp.endpoint
          value: http://otel-collector:4317