#FROM quay.io/hummingbird/openjdk:25-runtime
FROM registry.access.redhat.com/hi/openjdk:25
#FROM registry.access.redhat.com/hi/openjdk:25-runtime-fips
ENV LANGUAGE='en_US:en'
# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=65532 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=65532 target/quarkus-app/*.jar /deployments/
COPY --chown=65532 target/quarkus-app/app/ /deployments/app/
COPY --chown=65532 target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 65532
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
#ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
CMD ["java", "-Dquarkus.http.host=0.0.0.0","-Djava.util.logging.manager=org.jboss.logmanager.LogManager","-jar", "/deployments/quarkus-run.jar"]